Repository codingBottle/CoPro-iOS, pull requests merged in 2024-02, with the labels that each got.

#26 [Feat] #12 #23 - CardView & Custom Font,Color
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Network/API/Card/CardAPI.swift
  CoPro/CoPro/Network/DTO/Card/CardDTO.swift
  CoPro/CoPro/Network/Router/CardRouter/CardRouter.swift
  CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
  CoPro/CoPro/Presentation/Card/View/CardView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCard.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
  CoPro/CoPro/Presentation/Card/View/SlideCardView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/Login/View/LoginView.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
  CoPro/CoPro/Resource/Color/Color.swift
  CoPro/CoPro/Resource/Font/Font.swift
  CoPro/CoPro/Resource/Font/Pretendard-Black.otf
  CoPro/CoPro/Resource/Font/Pretendard-Bold.otf
  CoPro/CoPro/Resource/Font/Pretendard-ExtraBold.otf
  CoPro/CoPro/Resource/Font/Pretendard-ExtraLight.otf
  CoPro/CoPro/Resource/Font/Pretendard-Light.otf
  CoPro/CoPro/Resource/Font/Pretendard-Medium.otf
  CoPro/CoPro/Resource/Font/Pretendard-Regular.otf
  CoPro/CoPro/Resource/Font/Pretendard-SemiBold.otf
  CoPro/CoPro/Resource/Font/Pretendard-Thin.otf
Labels: 📬 API, ✨ Feature

#28 [Fix] 코드 도둑놈 혼내주기
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/DTO/Card/CardDTO.swift
Labels: 🐞 BugFix

#30 [Feat] #27 - Signin With Apple
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/CoProDebug.entitlements
  CoPro/CoPro/CoProRelease.entitlements
  CoPro/CoPro/Presentation/Login/View/LoginView.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
Labels: ✨ Feature

#33 [Feat] #19 - MyProfile Part
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/xcshareddata/xcschemes/CoPro.xcscheme
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditCardTypeDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditCardTypeRequestBody.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditGitHubURLDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditGitHubURLRequestBody.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditMyProfileDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditMyProfileRequestBody.swift
  CoPro/CoPro/Network/DTO/MyProfile/MyProfileDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/MyWrittenCommentDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/ScrapPostDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/WritebyMeDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/getNickNameDuplicationDTO.swift
  CoPro/CoPro/Network/Router/MyProfileRouter/MyProfileRouter.swift
  CoPro/CoPro/Presentation/Base/ViewController/BaseViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyProfileDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyProfileModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyWrittenCommentDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/ScrapPostDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/WritebyMeDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/CardTypeSettingsTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/ConversionSettingsTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyCommentsTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileView.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
  CoPro/CoPro/Util/Component/AppController.swift
Labels: 🐞 BugFix, 📬 API, ✨ Feature

#34 [Feat] #31 - BottomTabBar
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
Labels: ✨ Feature

#37 [Feat] #35 - Refactor Google SignIn Firebase => Oauth2.0
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/DTO/Login/LoginDTO.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#38 [Feat] #35 - Refactor SignIn with Firebase => Oauth2.0
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Network/API/Card/CardAPI.swift
  CoPro/CoPro/Network/API/Login/GitHubLoginManager.swift
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/Config/Config.swift
  CoPro/CoPro/Network/DTO/Card/CardDTO.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
  CoPro/CoPro/Presentation/Card/View/CardView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#42 [Feat] #36 - Chat, My Profile miscellaneous updates & Login branching logic implementation
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/DTO/Login/CheckInitialLoginDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/MyProfileDTO.swift
  CoPro/CoPro/Network/Router/LoginRouter/LoginRouter.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/Chat/Model/Channel.swift
  CoPro/CoPro/Presentation/Chat/Model/ChannelFirestoreStream.swift
  CoPro/CoPro/Presentation/Chat/Model/ChatFirestoreStream.swift
  CoPro/CoPro/Presentation/Chat/Model/Message.swift
  CoPro/CoPro/Presentation/Chat/View/ChannelTableViewCell.swift
  CoPro/CoPro/Presentation/Chat/View/CustomAvatarView.swift
  CoPro/CoPro/Presentation/Chat/View/CustomMessageContentCell.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyProfileDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/CardTypeSettingsTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyCommentsTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileView.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#46 [Refactor] Github Signin Error Alert & BottomTabBar Icon
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
Labels: 🔨 Refactor

#50 [Feat] #47 - 관심프로필 화면 추가
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Card/CardAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/LikeProfileDTO.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/LikeProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 📬 API, ✨ Feature

#51 Feat/#43
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/xcshareddata/xcschemes/CoPro.xcscheme
  CoPro/CoPro/Application/AppDelegate.swift
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/API/Notification/NotificationAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditMyProfileDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/MyProfileDTO.swift
  CoPro/CoPro/Network/DTO/Notification/FcmTokenDTO.swift
  CoPro/CoPro/Network/DTO/Notification/FcmTokenRequestBody.swift
  CoPro/CoPro/Network/Router/NotificationRouter/NotificationRouter.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/Chat/Model/Channel.swift
  CoPro/CoPro/Presentation/Chat/Model/ChannelFirestoreStream.swift
  CoPro/CoPro/Presentation/Chat/View/ChannelTableViewCell.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyProfileDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor, ✨ Feature

#57 [Refactor] #56 - UIupdate & BottomTabBar Icon / Fix OnboardingFlow
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Card/View/CardView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/LikeProfileViewController.swift
Labels: 🐞 BugFix, 🔨 Refactor

#61 [Fix] CardUI Error Fix
  CoPro/CoPro/Network/API/Card/CardAPI.swift
  CoPro/CoPro/Presentation/Card/View/CardView.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
Labels: 🐞 BugFix

#66 [Feat] #65 - CardView BugFix & UIupdate
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Network/API/Card/CardAPI.swift
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
Labels: 🐞 BugFix, 🎨 Style

#72 [Feat] #70 - NotificationList View
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Notification/NotificationListAPI.swift
  CoPro/CoPro/Network/DTO/Notification/NotificationListDTO.swift
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Notification/View/NotificationListCell.swift
  CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
Labels: 📬 API, ✨ Feature

#74 [Feat] #73 - Main Scroll Image Update
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
  CoPro/CoPro/Resource/AssetsCatalog/Image.xcassets/main_slider_image1.imageset/Contents.json
  CoPro/CoPro/Resource/AssetsCatalog/Image.xcassets/main_slider_image1.imageset/Group 1 (3).svg
Labels: 🎨 Style, ✨ Feature

#79 [Fix] #78 - Fix Login Flow
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
Labels: 🐞 BugFix

#77 [Fix] #59 - Fix Bugs
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
  CoPro/CoPro/Presentation/Main/Model/BoardDataModel.swift
  CoPro/CoPro/Presentation/Main/View/CommentChildTableViewCell.swift
  CoPro/CoPro/Presentation/Main/View/CommentTableViewCell.swift
  CoPro/CoPro/Presentation/Main/View/noticeBoardTableViewCell.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/ReportBottomSheetViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/SearchBarViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/SearchResultViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/SortBottomSheetViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/freeViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/noticeViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/selectBoardBottomSheetViewController.swift
  CoPro/CoPro/Resource/AssetsCatalog/Assets.xcassets/AppIcon.appiconset/Contents.json
  CoPro/CoPro/Resource/Color/Color.swift
  CoPro/CoPro/Util/CustomClass/Checkbox.swift
  CoPro/CoPro/Util/Extension/UISegmented++.swift
Labels: 🐞 BugFix, 🎨 Style

#89 [Fix] #88 - Resolved duplicate data issue
  CoPro/CoPro/Application/Info.plist
  CoPro/CoPro/Network/API/Notification/NotificationListAPI.swift
  CoPro/CoPro/Network/DTO/Notification/NotificationListDTO.swift
  CoPro/CoPro/Presentation/Notification/View/NotificationListCell.swift
  CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
Labels: 🐞 BugFix

#90 Fix/#87
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Chat/OppositeInfoAPI.swift
  CoPro/CoPro/Network/DTO/Chat/OppositeInfoDTO.swift
  CoPro/CoPro/Network/DTO/Chat/OppositeInfoRequestBody.swift
  CoPro/CoPro/Network/DTO/MyProfile/ScrapPostDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/WritebyMeDTO.swift
  CoPro/CoPro/Network/Router/ChatRouter/ChatRouter.swift
  CoPro/CoPro/Presentation/Chat/View/OppositeInfoCardView.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/OppositeInfoCardViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/ScrapPostDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/WritebyMeDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
Labels: 🐞 BugFix, 📬 API, ✨ Feature

#92 [Feat] #91 - add Implement detail view for posts in MyProfile
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
Labels: 🐞 BugFix, ✨ Feature

#94 [Feat] #93 - add like button feature, UI style updated at Chat card
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/OppositeInfoCardViewController.swift
Labels: 🎨 Style, ✨ Feature

#96 [Fix] #95 - fixed GitHub alert Bug in Login flow & edit Github DTO
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/EditGitHubURLDTO.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 🐞 BugFix

#97 [Fix] #95 - Fix chat room creation and navigation flow bug
  CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
Labels: 🐞 BugFix

#102 [Fix] #100 - Chat notification API request changes & First login flow edit
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/Notification/ChattingNotificationRequestBody.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
Labels: 🐞 BugFix

#104 [Fix] #103 - Fix Missing 'Mobile' Toggle in createBoard, Hide Project Toggle in Channel View
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
Labels: 🐞 BugFix

#107 [Feat] #101 - NotificationList Navigation & SignoutMethod
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Presentation/MyProfile/View/MemberStatusTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/MyProfileView.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
  CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
Labels: ✨ Feature

#109 [Feat] #108 - Notification Tap Event
  CoPro/CoPro/Application/AppDelegate.swift
Labels: ✨ Feature

#111 [Feat] #110 - add Finalized Signout feature with updates
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: ✨ Feature
