Repository codingBottle/CoPro-iOS, pull requests merged in 2024-03, with the labels that each got.

#118 [Fix] #117 - fixes for bugs occurring during the first login
  CoPro/CoPro/Application/SceneDelegate.swift
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
Labels: 🐞 BugFix

#119 [Fix] - boardData Day formatter Error
  CoPro/CoPro/Presentation/Main/Model/BoardDataModel.swift
Labels: 🐞 BugFix

#121 [Feat] MarkdownView 추가 (공지사항만)
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Presentation/Main/Model/CommentDataModel.swift
  CoPro/CoPro/Presentation/Main/Model/DetailBoardDataModel.swift
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
Labels: ✨ Feature

#125 [Feat] mark down url link event
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
Labels: ✨ Feature

#127 [Fix] #126 - Update Firestore with new nickname on nickname change
  CoPro/CoPro/Presentation/Chat/Model/ChannelFirestoreStream.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 🐞 BugFix

#137 Feat/#136
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/DTO/MyProfile/ScrapPostDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/WritebyMeDTO.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyWrittenCommentDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/ScrapPostDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/WritebyMeDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/View/RelatedPostsToMeTavleViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 🐞 BugFix, ✨ Feature

#139 [Feat] MyProfile View, Chat View 1차 피드백 추가 적용
  CoPro/CoPro/Presentation/Chat/View/ChannelTableViewCell.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: ✨ Feature

#133 [Fix] #129 - Resolve bug causing infinite increase in likes
  CoPro/CoPro/Application/AppDelegate.swift
  CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
  CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
Labels: 🐞 BugFix

#143 [Refactor] - Navigation & BottomTabItems
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
  CoPro/CoPro/Presentation/Card/View/CardView.swift
  CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/MainFloatingViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyWrittenCommentDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/ScrapPostDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/Model/WritebyMeDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/LikeProfileViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
  CoPro/CoPro/Presentation/Notification/View/NotificationListCell.swift
  CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
Labels: 🔨 Refactor, 🎨 Style, ✨ Feature

#150 [Feat] Implemented comment-to-post navigation
  CoPro/CoPro/Network/DTO/MyProfile/MyWrittenCommentDTO.swift
  CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
  CoPro/CoPro/Presentation/MyProfile/Model/MyWrittenCommentDataModel.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
Labels: ✨ Feature

#152 [Feat] #151 - Added account deletion and profile picture editing
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/Login/WithDrawalDTO.swift
  CoPro/CoPro/Network/DTO/MyProfile/AddProfilePhoto.swift
  CoPro/CoPro/Network/DTO/MyProfile/DeleteProfilePhoto.swift
  CoPro/CoPro/Network/Router/LoginRouter/LoginRouter.swift
  CoPro/CoPro/Network/Router/MyProfileRouter/MyProfileRouter.swift
  CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
  CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 📬 API, ✨ Feature

#153 [Fix] #141 - fix uri
  CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
Labels: 🔨 Refactor

#154 [ Refactor] #151 - Refactored profile picture modification, My Profile label & renamed account deletion
  CoPro/CoPro.xcodeproj/project.pbxproj
  CoPro/CoPro/Network/API/Login/LoginAPI.swift
  CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
  CoPro/CoPro/Network/DTO/Login/DeleteAccountDTO.swift
  CoPro/CoPro/Network/Router/LoginRouter/LoginRouter.swift
  CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
  CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
Labels: 🔨 Refactor

#156 [Fix] Fix bug in Scrap posts
  CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
Labels: 🐞 BugFix
